### ISSUE TITLE
game crash when leaving editor too quickly after opening

### ISSUE THREAD

**Issue by ezio416** [XertroV/tm-editor-plus-plus#12]
When opening maps (especially with a high number of blocks/items) and quickly leaving the editor afterwards, the game will crash with this plugin enabled. This is not exclusive to this plugin, it seems to happen with Editor Helpers as well, but I've now tested with each being enabled/disabled and both independently cause the crash. I'm thinking there's some reference in the editor being held onto that the game doesn't like.

Sometimes the game doesn't fully crash, but I'll get this error, presumably due to caching being interrupted (ghost blocks in this case):
![Screenshot 2024-03-20 171156](https://github.com/XertroV/tm-editor-plus-plus/assets/37951898/f967f022-2503-4fb2-8ff2-06641581a845)

Issue for Editor Helpers in case something is found in common between these: https://github.com/skybaks/tm-editor-helpers/issues/76

It now actually seems to not really depend on how much stuff is in a map, rather how many custom items I have (~18,000)

**Comment by XertroV** [comment]
This should have been fixed in the latest version

**Comment by ezio416** [comment]
Sorry but this is not fixed, I still occasionally get the crash with the latest version from this repo, whether or not Editor Helpers is also enabled. It is however fixed now in the Editor Helpers issue I linked (never crashes with E++ disabled), so probably worth looking into how that was done

**Comment by XertroV** [comment]
I think this is properly fixed now right? Please reopen or comment if not.
